import {
  Inter,
  Playfair_Display,
  Mulish,
  Space_Grotesk,
} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const playFair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-play-fair",
});
const mulish = Mulish({ subsets: ["latin"], variable: "--font-mulish" });
const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
